### ISSUE TITLE
Converted files are saved with original file extension

### ISSUE THREAD

**Issue by cniklas** [delfimov/imagemin-avif#1]
First of all: This thing works great!

The only thing I stumbled upon was the fact that the newly created files still have their original file name (`.jpg` in my case).
Any ideas why they don't end with `.avif` and how to fix it?

**Comment by delfimov** [comment]
Rename avif file to whatever you like. I do it like this:

`
.pipe(imagemin([avif({ quality: 50 })]))
.pipe(rename((path) => (path.extname += ".avif")))
`

**Comment by benjibee** [comment]
Any suggestion if using this with other imagemin plugins? The above example wouldn't work in this case.

**Comment by cenkakay** [comment]
> Rename avif file to whatever you like. I do it like this:
> 
> `.pipe(imagemin([avif({ quality: 50 })])) .pipe(rename((path) => (path.extname += ".avif")))`

Where we gonna put that code? Could you share full code please?

**Comment by emera1d** [comment]
Just use sharp instead. 

import sharp from 'sharp';
const convertBufferToAvif = options => async buffer => {
	return await sharp(buffer)
		.avif({ quality: 50, lossless: false, chromaSubsampling: '4:2:0' })
		.toBuffer()
		.catch((err) => console.log(err));
};
