### ISSUE TITLE
Update sharp to fix Chrome 93 and up from rendering avif images

### ISSUE THREAD

**Issue by joshunger** [delfimov/imagemin-avif#4]
Chrome 93 and up is going to reject AVIF images that are missing the 'pixi' box required by the AVIF specification.

See
- https://bugs.chromium.org/p/chromium/issues/detail?id=1198455
- https://github.com/lovell/sharp/issues/2666

**Comment by delfimov** [comment]
Just updated Sharp to the latest 0.28.3, but as far as I understood this issue will be fixed in 0.29 (https://github.com/lovell/sharp/issues/2666).
